### ISSUE TITLE
Responsive Nav Button Styling (Nice to Have)

### ISSUE THREAD

**Issue by emmasf** [bjornmeansbear/rwdfruhoh.ookb.co#16]
It's so out of sync with the rest of the site. I can't seem to kill it, though! If we have time, let's make it blue and flat.

**Comment by bjornmeansbear** [comment]
I changed it to at least say "Menu" instead, which they requested… do you still think it should be flat?

**Comment by emmasf** [comment]
Yes, but I don't think it's critical.
