### ISSUE TITLE
Project Page Arrow problem in Chrome

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/rwdfruhoh.ookb.co#2]
Paging arrows on project page don't show in chrome; focusable area is outermost 1 px only.

**Comment by bjornmeansbear** [comment]
@emmasf Problem solved with this: https://github.com/bjornmeansbear/rwdfruhoh.ookb.co/commit/af31dfe79d9011f2658cb23c1ea09eedb6d8aed8

Was a problem using the old fashioned text-indent: -99999px format... Chrome prefers a slightly more contemporary method; which works everywhere else as well.

**Comment by emmasf** [comment]
Excellent. What's the new method? Or I can just go look...

**Comment by bjornmeansbear** [comment]
{
text-indent: 100%;
white-space: nowrap;
overflow: hidden;
}

**Comment by bjornmeansbear** [comment]
http://www.zeldman.com/2012/03/01/replacing-the-9999px-hack-new-image-replacement/
