### ISSUE TITLE
Order of bios incorrect

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/rwdfruhoh.ookb.co#5]
Works locally, doesn't correctly order them when compiled on the live server

**Comment by webmasterkai** [comment]
I've noticed this on other sites too. For some reason ordering is different on the Heroku compiler.

**Comment by tlupfer** [comment]
I've noticed it as well, but it's not isolated to heroku. same site orders differently on my iMac and macbook.

**Comment by bjornmeansbear** [comment]
I've tried re-naming and telling ruhoh to sort by different things in the config file; somtimes it solves it, sometimes not...

**Comment by bjornmeansbear** [comment]
@webmasterkai @tlupfer This ordering problem is currently fixed — did either of you do anything to resolve this?

**Comment by tlupfer** [comment]
Nothing specific, although I did upgrade the heroku compiler to Ruhoh 2.4. We also put a compiler on one of Kai's servers to see if the problem was heroku specific. Are you using iron.io or cape.io as a webhook? It appears from the CNAME that you're still on the heroku amazon compiler.

**Comment by bjornmeansbear** [comment]
I'm using whatever thing you sent me a while ago, which yeah, is the heroku
amazon compiler

±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±

Kristian Bjørnard
Designer / Thinker / Sustainabilitist

ph:  507.301.8402
em: kristian.bjornard@gmail.com
w:   kristian.bjornard.com
w:   thesustainabilitist.com
twitter: @bjornmeansbear

**Comment by tlupfer** [comment]
Then it's either fixed with 2.4 or being random :) I'm testing it a bit more thoroughly on the other compiler while trying not to mess with the amazon one too much. keep me posted as to whether it seems to be consistently fixed.

**Comment by bjornmeansbear** [comment]
will do.
