### ISSUE TITLE
Any way to get #ids back into URLs?

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/rwdfruhoh.ookb.co#8]
Would like to be able to not refresh the page and have it go back to the initial load... not a big deal, but look into this after real issues are solved

**Comment by emmasf** [comment]
I had a solution for this earlier in the non-CAPE site...

**Comment by bjornmeansbear** [comment]
This is a ruhoh problem, I know you had it working correctly in the regular HTML version

**Comment by bjornmeansbear** [comment]
I got it working on the projects page… don't seem to be able to get them back on the "who we are" page however… not a big deal perhaps...
