### ISSUE TITLE
Icon BGs need to be gray in Active states of side-navs

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/rwdfruhoh.ookb.co#9]
Currently they are white.

**Comment by emmasf** [comment]
We may need to add new assets for this... they're white because we're handling color as cutouts.

**Comment by bjornmeansbear** [comment]
Yeah. Is there a vector file for them? I can just export with new BG color and switch in the :hover state

**Comment by emmasf** [comment]
Yes: in dropbox, RWDF > images > icon_production.fw.png
I just added gray assets for the small ones (e.g. category_arts_40gr.png) to the correct git folder, but if you want to modify them further they're all in there as vectors for easy export (assuming you've used Fireworks for that, it's super efficient at making slices).

**Comment by bjornmeansbear** [comment]
fixed: https://github.com/bjornmeansbear/rwdfruhoh.ookb.co/commit/8177f409a53652863ed0645c55218570104431ab
